version: '2.1'
services:
  elasticsearch:
    build:
      context: ./custom/elasticsearch/2.4/
    image: custom/elasticsearch2.4:latest
#    build:
#      context: ./custom/elasticsearch/5.0/
#    image: custom/elasticsearch5.0:latest
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data