version: '2.1'
services:
  elasticsearch:
#    build:
#      context: ./sources/elasticsearch/5/
#    image: custom/elasticsearch:latest
    image: elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data